[package]
edition = "2018"
name = "rsx_ui"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyon = "0.46.0"
macroquad = "0.3.7"
rsx-parser = {git = "https://github.com/nmpribeiro/rsx-parser.git"}
rsx_loader = {path = "../rsx_loader"}
snd = "0.0.0"
uuid = {version = "0.8", features = ["v4"]}
