[package]
edition = "2018"
name = "rust_jsx_app"
resolver = "2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
android_logger = "0.10.1"
cgmath = "0.18"
env_logger = "0.9"
image = "0.23"
log = "0.4"
pollster = "0.2"
# wgpu = "0.9.0"
web-sys = "0.3.51"
wgpu = {git = "https://github.com/gfx-rs/wgpu.git"}
winit = {git = "https://github.com/nmpribeiro/winit.git", branch = "fix/ios"}
# winit = {path = "../github/winit"}

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.10.1"
jni = "0.19.0"
ndk-glue = {version = "0.4.0", features = ["logger"]}

# Docs: https://lib.rs/crates/cargo-quad-apk
[package.metadata.android.sdk]
min_sdk_version = 16
target_sdk_version = 29

[package.metadata.android]
android_version = 30
package_name = "io.nmpribeiro.rust_jsx_app"
# DEBUG
# build_targets = ["armv7-linux-androideabi"]
# ALL
# build_targets = [ "armv7-linux-androideabi", "aarch64-linux-android", "i686-linux-android", "x86_64-linux-android" ]
assets = "assets/"
# USER DEFINED
label = "Rust JSX UI"
# version_code = 1
# version_name = "Bambi"

[lib]
crate-type = ["staticlib", "lib", "cdylib"]

[profiles.dev]
apple-universal = true

[profiles.release]
apple-universal = true
