name: app
options:
  bundleIdPrefix: com.rust
configs:
  Debug: debug
  Release: release
targets:
  cargo_ios:
    type: ""
    platform: iOS
    legacy:
      toolPath: /bin/sh
      arguments: "build_rust_deps.sh"
      workingDirectory: "."
  app:
    sources: src
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    scheme:
      environmentVariables:
        - variable: RUST_BACKTRACE
          value: 1
          isEnabled: true
        - variable: RUST_LOG
          value: info
          isEnabled: true
        - variable: METAL_DEVICE_WRAPPER_TYPE
          value: 1
          isEnabled: true
    settings:
      base:
        OTHER_LDFLAGS: ["$(inherited)", "-lrust_jsx_app"]
        ENABLE_BITCODE: NO
        CLANG_CXX_LANGUAGE_STANDARD: c++14
        CLANG_CXX_LIBRARY: libc++
      configs:
        debug:
          HEADER_SEARCH_PATHS: ["$(inherited)", "src/"]
          LIBRARY_SEARCH_PATHS: ["$(inherited)", "../target/universal/debug"]
        release:
          HEADER_SEARCH_PATHS: ["$(inherited)", "src/"]
          LIBRARY_SEARCH_PATHS: ["$(inherited)", "../target/universal/release"]
    dependencies:
      - sdk: OpenGLES.framework
      - sdk: Metal.framework
      - sdk: GLKit.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - target: cargo_ios
        embed: false
    info:
      path: src/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
