name: app

options:
  bundleIdPrefix: com.rust
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    iOS: "12.0"

settings:
  CLANG_CXX_LANGUAGE_STANDARD: c++17
  CLANG_CXX_LIBRARY: libc++
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

configs:
  Debug: debug
  Release: release
targets:
  cargo_ios:
    type: ""
    platform: iOS
    legacy:
      toolPath: /bin/sh
      arguments: "build_rust_deps.sh"
      workingDirectory: "."
  app:
    sources:
      - Sources
      - LaunchScreen.storyboard
      - path: assets
        type: folder
        buildPhase: resources
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    scheme:
      environmentVariables:
        - variable: RUST_BACKTRACE
          value: 1
          isEnabled: true
        - variable: RUST_LOG
          value: info
          isEnabled: true
        - variable: METAL_DEVICE_WRAPPER_TYPE
          value: 1
          isEnabled: true
    settings:
      base:
        OTHER_LDFLAGS: ["$(inherited)", "-lruinx"]
        ENABLE_BITCODE: NO
        CLANG_CXX_LANGUAGE_STANDARD: c++14
        CLANG_CXX_LIBRARY: libc++
      configs:
        debug:
          HEADER_SEARCH_PATHS: ["$(inherited)", "Sources/"]
          LIBRARY_SEARCH_PATHS: ["$(inherited)", "../target/universal/debug"]
        release:
          HEADER_SEARCH_PATHS: ["$(inherited)", "Sources/"]
          LIBRARY_SEARCH_PATHS: ["$(inherited)", "../target/universal/release"]
    dependencies:
      # - sdk: OpenGLES.framework
      - sdk: Metal.framework
      # - sdk: GLKit.framework
      # - sdk: CoreAudio.framework
      # - sdk: AudioToolbox.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      # - sdk: CoreFoundation.framework
      - target: cargo_ios
        embed: false
    info:
      path: Sources/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
